;title=minFS
;version=1.0.0
;creator=minbbb

[Status]
;mode=table
;alignment=left
;polling=true
ini_file sdmc:/switch/minfs.ini
'IP'='{local_ip}'
'Port'='{ini_file(server,port)}'
'Start path'='{ini_file(server,start_path)}'

[*Server Port]
;mode=option
list_source '(8080, 8081, 8082, 9000, 80)'
set-ini-val sdmc:/switch/minfs.ini server port {list_source(*)}
set-footer '{list_source(*)}'
notify-now 'Port set to {list_source(*)}. Reboot module to apply'
refresh-to 'Status'

[Logging]
;mode=toggle?off
file_source '/atmosphere/contents/420000000007E5AC/flags/logging.flag'
on:
touch /atmosphere/contents/420000000007E5AC/flags/logging.flag
off:
delete /atmosphere/contents/420000000007E5AC/flags/logging.flag

[Clear Log]
delete /switch/minFS.log
notify-now Log cleared

[View Log]
;mode=table
;alignment=left
;wrapping_mode=char
list_file_source /switch/minFS.log
